-- Generated from generator/demo_specs/aws-malaysia-oil-gas-esg.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-malaysia-oil-gas-esg
-- This is the schema that is actually deployed for MY_OIL_GAS_ESG.

-- Alerts fire on the top tail of Carbon Intensity
-- (higher is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.91) WITHIN GROUP (ORDER BY KPI_CARBON_INTENSITY) AS T
  FROM RAW.EMISSION_RECORDS
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_CARBON_INTENSITY >= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_CARBON_INTENSITY), 2) AS AVG_CARBON_INTENSITY,
  ROUND(AVG(f.KPI_METHANE_LEAKS), 2) AS AVG_METHANE_LEAKS,
  ROUND(AVG(f.KPI_FLARING_REDUCTION), 2) AS AVG_FLARING_REDUCTION,
  ROUND(AVG(f.KPI_PLATFORMS), 2) AS AVG_PLATFORMS,
  ROUND(AVG(f.KPI_NET_ZERO_GAP), 2) AS AVG_NET_ZERO_GAP
FROM RAW.EMISSION_RECORDS f
JOIN RAW.CLIMATE_BENCHMARKS e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_CARBON_INTENSITY), 2) AS AVG_CARBON_INTENSITY,
  ROUND(AVG(f.KPI_METHANE_LEAKS), 2) AS AVG_METHANE_LEAKS,
  ROUND(AVG(f.KPI_FLARING_REDUCTION), 2) AS AVG_FLARING_REDUCTION,
  ROUND(AVG(f.KPI_PLATFORMS), 2) AS AVG_PLATFORMS,
  ROUND(AVG(f.KPI_NET_ZERO_GAP), 2) AS AVG_NET_ZERO_GAP
FROM RAW.EMISSION_RECORDS f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_CARBON_INTENSITY) AS KPI_CARBON_INTENSITY, AVG(KPI_METHANE_LEAKS) AS KPI_METHANE_LEAKS, AVG(KPI_FLARING_REDUCTION) AS KPI_FLARING_REDUCTION, AVG(KPI_PLATFORMS) AS KPI_PLATFORMS, AVG(KPI_NET_ZERO_GAP) AS KPI_NET_ZERO_GAP FROM RAW.EMISSION_RECORDS),
     en AS (SELECT SUM(KPI_SCOPE_1_2) AS KPI_SCOPE_1_2, SUM(KPI_CCS_CAPACITY) AS KPI_CCS_CAPACITY FROM RAW.CLIMATE_BENCHMARKS)
  SELECT 1 AS SORT_ORDER, 'Carbon Intensity' AS TITLE, KPI_CARBON_INTENSITY AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_CARBON_INTENSITY), 1) AS DECIMAL(38,1))) || ' ' || 'kgCO2e/boe' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'Methane Leaks' AS TITLE, KPI_METHANE_LEAKS AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_METHANE_LEAKS)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'Flaring Reduction' AS TITLE, KPI_FLARING_REDUCTION AS VALUE_NUM, '-' || TO_VARCHAR(CAST(ROUND((KPI_FLARING_REDUCTION)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Platforms' AS TITLE, KPI_PLATFORMS AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_PLATFORMS)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'Scope 1+2' AS TITLE, KPI_SCOPE_1_2 AS VALUE_NUM, TO_VARCHAR(CAST(ROUND(((KPI_SCOPE_1_2) / 1000000), 1) AS DECIMAL(38,1))) || 'M' || ' ' || 'tCO2e' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'CCS Capacity' AS TITLE, KPI_CCS_CAPACITY AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_CCS_CAPACITY), 1) AS DECIMAL(38,1))) || ' ' || 'MT/yr' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 7 AS SORT_ORDER, 'Net Zero Gap' AS TITLE, KPI_NET_ZERO_GAP AS VALUE_NUM, '-' || TO_VARCHAR(CAST(ROUND((KPI_NET_ZERO_GAP)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
