-- ============================================================================
-- 99_RESET.SQL — Reset ESG & Carbon Emissions Monitoring to clean demo state
-- ============================================================================
USE DATABASE OIL_GAS_ESG;

-- Suspend tasks during demo
ALTER TASK IF EXISTS APP.TASK_PARSE_ESG_REPORTS SUSPEND;
ALTER TASK IF EXISTS APP.TASK_COMPUTE_SCOPE2 SUSPEND;
ALTER TASK IF EXISTS APP.TASK_REFRESH_ICEBERG SUSPEND;

-- Force refresh Dynamic Tables
ALTER DYNAMIC TABLE CURATED.FACILITY_EMISSIONS_SUMMARY REFRESH;
ALTER DYNAMIC TABLE CURATED.EMISSIONS_TIMESERIES REFRESH;
ALTER DYNAMIC TABLE CURATED.SCOPE2_CALCULATION REFRESH;
ALTER DYNAMIC TABLE CURATED.REDUCTION_PROGRESS REFRESH;

-- Verify key demo numbers
-- SELECT COUNT(*) FROM OIL_GAS_ESG.RAW.EMISSION_RECORDS → 50000
-- SELECT COUNT(*) FROM OIL_GAS_ESG.RAW.FACILITIES → 30
-- SELECT SUM(CO2E_TONNES) FROM OIL_GAS_ESG.CURATED.FACILITY_EMISSIONS_SUMMARY → ~2400000

-- Resume tasks
ALTER TASK IF EXISTS APP.TASK_REFRESH_ICEBERG RESUME;
ALTER TASK IF EXISTS APP.TASK_COMPUTE_SCOPE2 RESUME;
ALTER TASK IF EXISTS APP.TASK_PARSE_ESG_REPORTS RESUME;
